apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: searxng-application-system
  namespace: webgrip
  title: Searxng Application System
  description: |
    Searxng is a free and open source metasearch engine that aggregates results from various search engines.
  labels:
    tier: "3"
  annotations:
    github.com/project-slug: webgrip/searxng-application
    backstage.io/adr-location: docs/adrs
    backstage.io/techdocs-ref: dir:./docs/techdocs
    simpleicons.org/icon-slug: searxng
  tags:
    - searxng
  links:
    - url: https://searxng.staging.k8s.webgrip.nl
      title: Staging URL
      icon: dashboard
      type: website
    - url: https://github.com/webgrip/searxng-application
      title: Source Code
      icon: searxng
      type: source
spec:
  owner: group:webgrip/infrastructure
  domain: webgrip/operations-domain
  type: product
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: searxng-application
  namespace: webgrip
  title: searxng
  description: |
    Searxng is a free and open source metasearch engine that aggregates results from various search engines.
  labels:
    tier: "3"
  annotations:
    github.com/project-slug: webgrip/searxng-application
    backstage.io/techdocs-ref: dir:./docs/techdocs
    simpleicons.org/icon-slug: searxng
  tags:
    - searxng
  links:
    - url: https://searxng.staging.k8s.webgrip.nl
      title: Staging URL
      icon: dashboard
      type: website
    - url: https://github.com/webgrip/searxng-application
      title: Source Code
      icon: searxng
      type: source
spec:
  type: service
  lifecycle: development
  owner: group:webgrip/infrastructure
  system: searxng-application-system
