services:
  searxng:
    container_name: searxng
    image: webgrip/searxng:latest
    build:
      context: ./ops/docker/searxng
      dockerfile: Dockerfile
    pull_policy: never
    ports:
      - "8080:8080"
    volumes:
      - ./ops/docker/searxng/config:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

