apiVersion: v2
name: searxng-application
description: "Helm Chart for deploying SearxNG on Kubernetes, a privacy-respecting, hackable metasearch engine."
type: application
version: 0.2.0
appVersion: "2025.4.1"
dependencies:
  - name: searxng
    version: 10.3.4
    repository: oci://tccr.io/truecharts
  - name: common-helpers
    repository: oci://ghcr.io/webgrip/common-charts
    version: 1.0.13
