namespace: searxng-application

_shared_config:
  hostname: &hostname searxng.staging.k8s.webgrip.nl
  url: &url https://searxng.staging.k8s.webgrip.nl

searxng:
  image:
    repository: webgrip/searxng-application
    tag: "latest"
    pullPolicy: Always

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

  service:
    main:
      ports:
        main:
          enabled: true
          port: 8080
          protocol: http

  ingress:
    main:
      enabled: true
      ingressClassName: ingress-traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-traefik
        # traefik.ingress.kubernetes.io/router.middlewares: "ingress-traefik-ryan-home-ip-allow-list@kubernetescrd,ingress-traefik-office-ip-allow-list@kubernetescrd"
      hosts:
        - host: *hostname
          paths:
            - path: /
              pathType: Prefix
              service:
                name: searxng-application
                port: 8080
      tls:
        - secretName: letsencrypt-searxng-application
          hosts:
            - *hostname

  env:
    TZ: Europe/Amsterdam
    INSTANCE_NAME: searxng-application
    BASE_URL: *url
    SEARXNG_REDIS_URL: redis://searxng-application-redis.searxng-application.svc.cluster.local:6379/0
    SEARXNG_SEARCH_FORMATS: html,json
    SEARXNG_SECRET:
      valueFrom:
        secretKeyRef:
          name: searxng-application-secrets
          key: searxng-secret

redis:
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 1Gi
  replica:
    replicaCount: 0
