name: '[Workflow] On Source Change'

concurrency:
  group: push-${{ github.branch }}

on:
  push:
    branches:
      - 'main'
    paths:
      - 'ops/**'
      - 'src/**'
      - '.releaserc.json'
      - '.github/workflows/on_source_change.yml'

jobs:
  release:
    name: 'Release'
    uses: webgrip/workflows/.github/workflows/semantic-release.yml@main

  determine-changed-secrets:
    name: "Secrets"
    uses: webgrip/workflows/.github/workflows/determine-changed-directories.yml@main
    with:
      inside-dir: 'ops/secrets'
      max-level: 1

  deploy-changed-secrets:
    name: "Deploy Changed Secrets"
    needs: [ determine-changed-secrets ]
    if: needs.determine-changed-secrets.outputs.matrix != '[]'
    uses: webgrip/workflows/.github/workflows/helm-charts-deploy.yml@main
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      DIGITAL_OCEAN_API_KEY: ${{ secrets.DIGITAL_OCEAN_API_KEY }}
      SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
    with:
      paths: ${{ needs.determine-changed-secrets.outputs.matrix }}

  build:
    name: 'Build'
    needs: [ release ]
    if: >
      always()
      && needs.release.result == 'success'
      && needs.release.outputs.version != ''
    uses: webgrip/workflows/.github/workflows/docker-build-and-push.yml@main
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    with:
      docker-context: './ops/docker/searxng'
      docker-file: 'Dockerfile'
      docker-tags: |
        webgrip/searxng-application:latest
        webgrip/searxng-application:${{ needs.release.outputs.version }}

  deploy-application:
    name: 'Deploy'
    needs: [ release, build, deploy-changed-secrets ]
    if: >
      always()
      && needs.build.result == 'success'
    uses: webgrip/workflows/.github/workflows/helm-chart-deploy.yml@main
    secrets:
      DIGITAL_OCEAN_API_KEY: ${{ secrets.DIGITAL_OCEAN_API_KEY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    with:
      environment: 'staging'
      path: './ops/helm/searxng-application'
      tag: ${{ needs.release.outputs.version }}
